name: 0.21.0plus6 Test OpenSpace macOS installer script

on:
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: macos-15

    steps:
      - name: Create logs directory
        run: mkdir -p logs

      - name: Download OpenSpace installer
        run: |
          curl -L -o install_openspace_applesilicon.sh \
            https://github.com/hn-88/OpenSpace-AppleSiliconMac/releases/download/v0.21.0plus6/install_openspace_applesilicon.sh

      - name: run installer script
        run: |
          xattr -rd com.apple.quarantine install_openspace_applesilicon.sh || echo "No quarantine flag on script"
          bash install_openspace_applesilicon.sh
          

      - name: Remove quarantine from installed files
        run: |
          if [ -d "$HOME/OpenSpace" ]; then
            echo "✅ Found installation directory"
            xattr -r -d com.apple.quarantine "$HOME/OpenSpace/bin/OpenSpace.app" || echo "No quarantine flag found on installed files"
          else
            echo "❌ Installation directory not found"
            exit 1
          fi

      - name: Verify .app bundle
        run: |
          if [ -d "$HOME/OpenSpace/bin/OpenSpace.app" ]; then
            echo "✅ Found OpenSpace.app"
          else
            echo "❌ OpenSpace.app not found at expected location"
            exit 1
          fi

      - name: Check Applications Shortcut
        run: |
          SHORTCUT="/Applications/OpenSpace"
          TARGET="$HOME/OpenSpace/bin/OpenSpace.app"
          if [ -L "$SHORTCUT" ]; then
            LINK_TARGET=$(readlink "$SHORTCUT")
            echo "🔗 Shortcut found: $SHORTCUT → $LINK_TARGET"
            if [ "$LINK_TARGET" = "$TARGET" ]; then
              echo "✅ Shortcut points to correct target"
            else
              echo "⚠️ Shortcut exists but points to wrong target"
              exit 1
            fi
          else
            echo "❌ No shortcut found at $SHORTCUT"
            exit 1
          fi

      - name: Run OpenSpace for 5 minutes
        run: | 
          open $HOME/OpenSpace/bin/OpenSpace.app || echo "Allow errors due to headless runner."
          sleep 300

      - name: Run OpenSpace for 5 minutes from executable with -b
        run: |
          cd $HOME/OpenSpace
          ./bin/OpenSpace.app/Contents/MacOS/OpenSpace -b || echo "Allow errors due to headless runner."
          sleep 300

