name: consolidated-errors-arm64

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  OPENSPACE_VERSION: "0.21.0post-rc1"
  THIS_REPO_PATH: "/Users/runner/work/OpenSpace-AppleSiliconMac/OpenSpace-AppleSiliconMac" 

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: get openspace code for a particular release
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        git clone --recursive https://github.com/hn-88/OpenSpace.git "$openSpaceHome"
        cd "$openSpaceHome"
        git checkout ToCompileOnMacOS --recurse-submodules
        mkdir build
        cd build

    - name: Update Homebrew and Install GLM, jq, Python
      run: |
        brew update
        brew install glm jq python

    - name: Install compiledb (Python tool)
      run: |
        brew install compiledb

    - name: get patched Ghoul
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/ext"
        rm -rf ghoul
        git clone https://github.com/hn-88/Ghoul.git --branch MacOSfixes --recursive

    - name: patch touchbar
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        # cp -v src-interaction-touchbar.mm "$openSpaceHome/src/interaction/touchbar.mm"

    - name: patch verifier.inl and other files
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        # cp -v include-openspace-documentation-verifier.inl "$openSpaceHome/include/openspace/documentation/verifier.inl"
        # cp -v modules-webgui-webguimodule.cpp "$openSpaceHome/modules/webgui/webguimodule.cpp"
        # cp -v modules-webbrowser-webbrowsermodule.cpp "$openSpaceHome/modules/webbrowser/webbrowsermodule.cpp"
        # cp -v ext-json-CMakeLists.txt "$openSpaceHome/ext/json/CMakeLists.txt"
        # cp -v src-documentation-verifier.cpp "$openSpaceHome/src/documentation/verifier.cpp"
        # cp -v modules-webbrowser-src-cefhost.cpp "$openSpaceHome/modules/webbrowser/src/cefhost.cpp"
        # cp -v include-openspace-util-json_helper.inl "$openSpaceHome/include/openspace/util/json_helper.inl"
    
    - name: Install dependencies
      run: |
        brew install glew boost freeimage mpv vulkan-headers vulkan-loader brotli gdal qt@6

    - name: Configure CMake (Xcode generator)
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome"
        cmake -G Ninja -S . -B build -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_STANDARD=20 -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0
        ls -l

    - name: Custom individual file compilationAdd commentMore actions
      run: |
        brew install jq
        chmod +x compile_all_from_compile_commands.sh
        ./compile_all_from_compile_commands.sh "$HOME/source/OpenSpace/build" "$HOME/source/OpenSpace/individual_build" || true
        cat "$HOME/source/OpenSpace/individual_build/compile_errors.txt"
          
    - name: Upload compile error log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: individual-compile-errors
        path: $HOME/source/OpenSpace/individual_build/compile_errors.txt
