name: Upload PKG to Draft Release

on:
  workflow_dispatch:

jobs:
  upload-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (required to create tags)
        uses: actions/checkout@v4

      - name: Set release version
        id: vars
        run: echo "tag=v0.21.0plus5" >> $GITHUB_OUTPUT

      - name: Get artifact download URL
        id: get_artifact_url
        run: |
          API_URL="https://api.github.com/repos/hn-88/OpenSpace-AppleSiliconMac/actions/artifacts/3551388018/zip"
          AUTH="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          ACCEPT="Accept: application/vnd.github+json"

          curl -sSL -H "$AUTH" -H "$ACCEPT" -D headers.txt -o /dev/null "$API_URL"
          DOWNLOAD_URL=$(grep -i "^location: " headers.txt | cut -d' ' -f2 | tr -d '\r\n')
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Download artifact
        run: |
          curl -L -o artifact.zip "${{ steps.get_artifact_url.outputs.download_url }}"

      - name: Unzip artifact
        run: |
          unzip artifact.zip -d unpacked

      - name: Find PKG file
        id: find_pkg
        run: |
          PKG_FILE=$(find unpacked -name "*.pkg" | head -n 1)
          echo "Found pkg: $PKG_FILE"
          echo "pkg_path=$PKG_FILE" >> $GITHUB_OUTPUT

      - name: Create tag if not exists
        run: |
          TAG=${{ steps.vars.outputs.tag }}
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Create draft release and upload pkg
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          tag_name: ${{ steps.vars.outputs.tag }}
          draft: true
          files: ${{ steps.find_pkg.outputs.pkg_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
